## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Data Science Service: Health care use cases."
stackDescription: "Data Science Service: Health care use cases."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - datas_drg_attachment_display_name
  - service_ports

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name
  - NumberOfAppVMs
  - autonomous_database_private_endpoint
  - autonomous_database_admin_password
  - analytics_instance_idcs_access_token
  - use_bastion_service
  - show_advanced 

- title: Networking Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:  
  - datas_vcn_display_name
  - VCN-CIDR
  - Public_Subnet-CIDR
  - Private_Subnet-CIDR
  - datas_drg_display_name

- title: Load Balancer Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape 

- title: Compute Optional Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - ssh_public_key 
  - instance_os
  - linux_os_version
  - Shape
  - FlexShapeOCPUS
  - FlexShapeMemory
  - BastionShape
  - BastionFlexShapeOCPUS
  - BastionFlexShapeMemory

- title: Autonomous Optional Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - autonomous_database_cpu_core_count
  - autonomous_database_db_name
  - autonomous_database_display_name 
  - autonomous_database_db_version
  - autonomous_database_is_auto_scaling_enabled
  - autonomous_database_data_storage_size_in_tbs
  - autonomous_database_db_workload
  - autonomous_database_license_model
  - autonomous_database_data_safe_status
  - autonomous_database_private_endpoint_label

- title: OAC Optional Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - analytics_instance_capacity_capacity_type
  - analytics_instance_capacity_capacity_value
  - analytics_instance_feature_set
  - analytics_instance_license_type
  - analytics_instance_name

- title: Catalog Optional Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - catalog_display_name

- title: DataScience Optional Configuration
  visible: 
      and:
        - show_advanced
  variables: 
  - project_display_name
  - notebook_session_display_name
  - DSNotebookShape
  - DSNotebookFlexShapeOCPUS
  - DSNotebookFlexShapeMemory

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your Infrastructure will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  NumberOfAppVMs:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 3
    title: "How many Application VMs"
    description: "Choose number of Application VMs to be deployed."

  autonomous_database_private_endpoint:
    type: boolean
    visibile: true
    default: false
    required: true
    title: "ADW Database Private Endpoint"
    description: "Check the box to deploy ADW Database with Private Endpoint."

  autonomous_database_private_endpoint_label:
    type: string
    required: false
    visible: 
      and:
        - autonomous_database_private_endpoint
    default: "ADWPrivateEndpoint"
    title: "ADW Database Private Endpoint Label"
    description: "Choose ADW Database Private Endpoint label."

  autonomous_database_admin_password:
    type: password
    required: true
    title: "ADW Database Password"
    description: "ADW Database Password for ADMIN user."
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  analytics_instance_idcs_access_token:
    type: text
    required: true
    title: "IDCS Acccess Token for OAC"
    description: "IDCS Acccess Token required by Oracle Analytics Cloud (OAC)."

  use_bastion_service:
    type: boolean
    visibile: true
    default: false
    required: false
    title: "Use OCI Bastion Service"
    description: "Check the box to use OCI Bastion Service instead of Bastion Host VM."

  # Optional Configuration

  datas_vcn_display_name: 
    type: string
    default: "DataScienceVCN"
    visible: true
    required: false
    title: "VCN Display Name"
    description: "Choose VCN Display Name"

  VCN-CIDR:  
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "VCN CIDR block where you want to create the solution resources."

  Public_Subnet-CIDR:  
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Public Subnet CIDR"
    description: "Subnet CIDR block where you want to create the solution resources."

  Private_Subnet-CIDR:  
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Private Subnet CIDR"
    description: "Subnet CIDR block where you want to create the solution resources."

  datas_drg_display_name:
    type: string
    default: "DataScience_DRG"
    visible: true
    required: false
    title: "DRG Display Name"
    description: "Choose DRG Display Name"

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  lb_shape:
    type: enum
    title: "Load Balancer Shape"
    description: "Load Balancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

    flex_lb_max_shape:
      type: enum
      required: false
      default: "100"
      title: "LB Flex Max Shape"
      description: "Choose Maximum Shape for Flex Load Balancer."
      enum:
        - "10"
        - "100"
        - "1000"
        - "400"
        - "8000"
      visible:
        and:
          - eq:
            - lb_shape 
            - "flexible"

  Shape:
    type: oci:core:instanceshape:name
    required: false
    visible: true
    default: "VM.Standard.E3.Flex"
    title: "User Application VMs Shape"
    description: "Choose User Application VMs Shape"
    dependsOn:
      compartmentId: ${compartment_ocid}

  FlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - Shape 
            - "VM.Standard.A3.Flex"
          - eq:
            - Shape 
            - "VM.Optimized3.Flex"

  FlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - Shape
            - "VM.Standard.E4.Flex"
          - eq:
            - Shape 
            - "VM.Standard.A3.Flex"
          - eq:
            - Shape 
            - "VM.Optimized3.Flex"

  BastionShape:
    type: oci:core:instanceshape:name
    required: false
    visible: true
    default: "VM.Standard.E3.Flex"
    title: "Bastion VM Shape"
    description: "Choose Bastion Shape"
    dependsOn:
      compartmentId: ${compartment_ocid}

  BastionFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A3.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  BastionFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Bastion Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - BastionShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - BastionShape
            - "VM.Standard.E4.Flex"
          - eq:
            - BastionShape 
            - "VM.Standard.A3.Flex"
          - eq:
            - BastionShape 
            - "VM.Optimized3.Flex"

  DSNotebookShape:
    type: oci:core:instanceshape:name
    required: false
    visible: true
    default: "VM.Standard.E3.Flex"
    title: "DataScience Notebook Shape"
    description: "Choose DataScience Notebook Shape"
    dependsOn:
      compartmentId: ${compartment_ocid}

  DSNotebookFlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "DataScience Notebook Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - DSNotebookShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - DSNotebookShape 
            - "VM.Standard.E4.Flex"
          - eq:
            - DSNotebookShape 
            - "VM.Standard.A3.Flex"
          - eq:
            - DSNotebookShape 
            - "VM.Optimized3.Flex"

  DSNotebookFlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "DataScience Notebook Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - DSNotebookShape 
            - "VM.Standard.E3.Flex"
          - eq:
            - DSNotebookShape
            - "VM.Standard.E4.Flex"
          - eq:
            - DSNotebookShape 
            - "VM.Standard.A3.Flex"
          - eq:
            - DSNotebookShape 
            - "VM.Optimized3.Flex"

  instance_os:
    type: enum
    required: false
    visible: false
    title: "Instance OS"
    description: "Choose Operating System that determines the operating system for User Application VMs."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: false
    title: "Instance OS version"
    description: "Choose Operating System version that determines the operating system version for User Application VMs."
    default: "8"
    enum:
      - "8"
      - "7.9"  

  autonomous_database_cpu_core_count:
    type: number
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    visible: true
    required: false
    title: "ADW database CPU core count"
    description: "Autonomous Data Warehouse (ADW) CPU core count"

  autonomous_database_db_name:
    type: string
    default: "aTFdb"
    visible: true
    required: false
    title: "ADW database name"
    description: "Autonomous Data Warehouse (ADW) Database name"

  autonomous_database_display_name:
    type: string
    default: "DataScienceADW"
    visible: true
    required: false
    title: "ADW database display name"
    description: "Autonomous Data Warehouse (ADW) Database display name"

  autonomous_database_db_version: 
    type: enum
    default: "19c"
    visible: true
    required: false
    title: "ADW database version"
    description: "Autonomous Data Warehouse (ADW) Database version"
    enum:
      - "19c"

  autonomous_database_is_auto_scaling_enabled: 
    type: boolean
    default: false 
    visible: true
    required: false
    title: "ADW database auto-scalling enabled"
    description: "Autonomous Data Warehouse (ADW) auto-scalling enabled"

  autonomous_database_data_storage_size_in_tbs: 
    type: number
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    visible: true
    required: false
    title: "ADW database data storage size in TBs"
    description: "Autonomous Data Warehouse (ADW) data storage size in terabytes."

  autonomous_database_db_workload:
    type: string
    visible: false
    required: false
    title: "ADW database DB workload"

  autonomous_database_license_model:
    type: enum
    default: "BRING_YOUR_OWN_LICENSE"
    visible: true
    required: false
    title: "ADW databaselicense model"
    description: "Autonomous Data Warehouse (ADW) license model."
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  autonomous_database_data_safe_status:
    type: enum
    default: "NOT_REGISTERED" 
    visible: true
    required: false
    title: "ADW database DataSafe status"
    description: "Autonomous Data Warehouse (ADW) DataSafe status."
    enum:
      - "NOT_REGISTERED"

  catalog_display_name:
    type: string
    default: "My_Data_Catalog"
    visible: true
    required: false
    title: "OCI DataCatalog display name"
    description: "OCI DataCatalog display name"

  analytics_instance_capacity_capacity_type:
    type: enum
    default: "OLPU_COUNT"
    visible: true
    required: false
    title: "OAC instance capacity type"
    description: "Oracle Analytics Cloud (OAC) instance capacity type"
    enum:
      - "OLPU_COUNT"

  analytics_instance_capacity_capacity_value:
    type: number
    default: 1
    minimum: 1
    maximum: 52
    multipleOf: 1
    required: false
    visible: true
    title: "OAC nstance capacity value"
    description: "Oracle Analytics Cloud (OAC) instance capacity value"

  analytics_instance_feature_set: 
    type: enum
    default: "ENTERPRISE_ANALYTICS"
    visible: true
    required: false
    title: "OAC instance feature set"
    description: "Oracle Analytics Cloud (OAC) instance feature set"
    enum:
      - "ENTERPRISE_ANALYTICS"

  analytics_instance_license_type: 
    type: enum
    default: "LICENSE_INCLUDED"
    visible: true
    required: false
    title: "OAC instance license_type"
    description: "Oracle Analytics Cloud (OAC) instance license_type"
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  analytics_instance_name:
    type: string
    default: "OAC"
    visible: true
    required: false
    title: "OAC instance name"
    description: "Oracle Analytics Cloud (OAC) instance name"

  project_display_name:
    type: string
    default: "DataScienceProject"
    visible: true
    required: false
    title: "OCI DataScience Project Display Name"
    description: "Choose OCI DataScience Project Display Name"

  notebook_session_display_name:
    type: string
    default: "DataScienceNotebookSession"
    visible: true
    required: false
    title: "OCI DataScience Notebook Session Display Name"
    description: "Choose OCI DataScience Notebook Session Display Name"

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"



